[package]
name = "efense"
version.workspace = true
authors.workspace = true
description = "Crate of efense holding shared tools, (with_std)"
documentation.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aya = { workspace = true }
efense_core = { path = "../lib_nostd" }
serde = { workspace = true, features = ["derive", "std"] }
time = { workspace = true }

[dev-dependencies]
serde_json = "1"
serde_yaml = "0.9"

[lib]
path = "lib.rs"
