[package]
name = "efense_ebpf"
description = """
Efense eBPF program for securty event monitoring and rule enforcement"""
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true
license = "GPL-2.0-only"
rust-version.workspace = true

[dependencies]
aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }
network-types = { workspace = true }
efense_core = { path = "../lib_nostd" }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "efense_ebpf_cli"
path = "main.rs"

[lib]
path = "lib.rs"

