[workspace]
resolver = "2"
members = [
    "src/cli",
    "src/ebpf",
    "src/lib_nostd",
    "src/lib",
]
default-members = ["src/cli", "src/lib_nostd", "src/lib"]

[workspace.package]
version = "0.1.0"
authors = ["Gris Ge <cnfourt@gmail.com>"]
description = "Linux tool for security monitor and protection"
documentation = "https://github.com/cathay4t/efense"
edition = "2024"
license = "Apache 2.0"
rust-version = "1.88"

[workspace.dependencies]
aya = { git = "https://github.com/aya-rs/aya", default-features = false }
aya-build = { git = "https://github.com/aya-rs/aya", default-features = false }
aya-ebpf = { git = "https://github.com/aya-rs/aya", default-features = false }
aya-log = { git = "https://github.com/aya-rs/aya", default-features = false }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya", default-features = false }

time = { version = "0.3", default-features = false, features = ["formatting", "parsing", "std"] }
clap = { version = "4.6.1", default-features = false, features = ["std"] }
env_logger = { version = "0.11.5", default-features = false }
libc = { version = "0.2.159", default-features = false }
log = { version = "0.4.22", default-features = false }
tokio = { version = "1.40.0", default-features = false }
which = { version = "6.0.0", default-features = false }
cargo_metadata = { version = "0.23.0", default-features = false }
network-types = { version = "0.2.0", default-features = false }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false, features = ["std"] }

[profile.release.package.efense_ebpf]
debug = 2
codegen-units = 1
strip = false
