[package]
name = "efctl"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aya = { workspace = true }
aya-log = { workspace = true }
env_logger = { workspace = true }
efense_core = { path = "../lib_nostd" }
efense = { path = "../lib" }
libc = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
    "sync",
] }
clap = { workspace = true, features = ["help", "usage"] }
serde_yaml = "0.9"
serde_json = { workspace = true }

[build-dependencies]
aya-build = { workspace = true }
cargo_metadata = { workspace = true }
# TODO(https://github.com/rust-lang/cargo/issues/12375): this should be an
# artifact dependency, but it's not possible to tell cargo to use
# `-Z build-std` to build it. Check aya document for more details
efense_ebpf = { path = "../ebpf" }

[[bin]]
name = "efctl"
path = "main.rs"
